### ISSUE TITLE
Does not compile on latest Zig

### ISSUE THREAD

**Issue by notramo** [joachimschmidt557/linenoize#20]
`sts.mem.copy` should be replaced with `@memcpy`

**Comment by Phytolizer** [comment]
FWIW the semantics differ a fair amount: with `@memcpy`, the slices need to be the same length and also not overlap. The direct replacement is `std.mem.copyForwards`.

**Comment by joachimschmidt557** [comment]
Thanks for the info, I've solved the issue with 60da07356154218ea4d427c258aa0fab093eb4f3.

**Comment by Phytolizer** [comment]
The fix is incomplete, there are 2 more usages in term.zig: https://github.com/joachimschmidt557/linenoize/blob/master/src/term.zig#L167-L170

**Comment by joachimschmidt557** [comment]
Thanks, fixed with a69e3764e32523c28717113da309bbee5dab66c4

**Comment by Phytolizer** [comment]
Thanks!
